import Footer from "./components/UI/Footer";
import Navbar from "./components/UI/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-white text-black`}>
        <nav>
          <Navbar />
        </nav>
        <main className="min-h-screen px-40">{children}</main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
